// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kzszyswgqasvtnmkqydx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt6c3p5c3dncWFzdnRubWtxeWR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMTQ2MDEsImV4cCI6MjA1NjU5MDYwMX0.4opZLJLL0flSnoXuIBJKO0TeMKpxhE0VREp3JwvUaBQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);